# Generated by Django 5.2.8 on 2025-11-27 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique identifiant le module (ex: INF101)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code du module",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du module"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "credits",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de crédits ECTS",
                        verbose_name="Crédits",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        help_text="Ex: S1, S2, Automne 2024",
                        max_length=20,
                        null=True,
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le module est actuellement actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Limite du nombre d'étudiants pouvant s'inscrire",
                        null=True,
                        verbose_name="Nombre maximum d'étudiants",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_modules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enseignant référent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'inscription est toujours active",
                        verbose_name="Inscription active",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Note obtenue (sur 20)",
                        max_digits=5,
                        null=True,
                        verbose_name="Note",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes additionnelles sur l'inscription",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="api.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(fields=["code"], name="api_module_code_6c9d57_idx"),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["teacher"], name="api_module_teacher_752ae4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["is_active"], name="api_module_is_acti_b6ee35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "module"], name="api_enrollm_student_05cf8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["is_active"], name="api_enrollm_is_acti_2ec6cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["enrollment_date"], name="api_enrollm_enrollm_5cc132_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "module")},
        ),
    ]
