# Generated by Django 5.2.8 on 2025-11-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_module_enrollment_module_api_module_code_6c9d57_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Document Word"),
                            ("docx", "Document Word"),
                            ("ppt", "PowerPoint"),
                            ("pptx", "PowerPoint"),
                            ("xls", "Excel"),
                            ("xlsx", "Excel"),
                            ("video", "Vidéo"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("link", "Lien externe"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de ressource",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Fichier à télécharger",
                        null=True,
                        upload_to="course_resources/%Y/%m/%d/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien externe si la ressource n'est pas un fichier",
                        null=True,
                        verbose_name="URL externe",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si la ressource est accessible à tous les étudiants du module",
                        verbose_name="Public",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Taille du fichier en octets",
                        null=True,
                        verbose_name="Taille du fichier (octets)",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="api.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Téléchargé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource de cours",
                "verbose_name_plural": "Ressources de cours",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["module"], name="api_courser_module__9e425b_idx"
                    ),
                    models.Index(
                        fields=["resource_type"], name="api_courser_resourc_bf969b_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="api_courser_is_publ_ff814b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Titre optionnel de la session",
                        max_length=200,
                        null=True,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Cours magistral"),
                            ("tutorial", "TD - Travaux dirigés"),
                            ("lab", "TP - Travaux pratiques"),
                            ("exam", "Examen"),
                            ("other", "Autre"),
                        ],
                        default="lecture",
                        max_length=20,
                        verbose_name="Type de session",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Salle physique ou lien de visioconférence",
                        max_length=200,
                        null=True,
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si la session est en visioconférence",
                        verbose_name="Session en ligne",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description ou notes sur la session",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="api.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de cours",
                "verbose_name_plural": "Sessions de cours",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["module", "date"], name="api_courses_module__d8d77c_idx"
                    ),
                    models.Index(
                        fields=["teacher", "date"],
                        name="api_courses_teacher_62395a_idx",
                    ),
                    models.Index(
                        fields=["date", "start_time"],
                        name="api_courses_date_02b1e8_idx",
                    ),
                ],
            },
        ),
    ]
