# Generated by Django 5.2.8 on 2025-11-27 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_courseresource_coursesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("normal", "Normale"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Annonce importante affichée en premier",
                        verbose_name="Épinglée",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'annonce est visible",
                        verbose_name="Active",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Étudiant"),
                            ("teacher", "Enseignant"),
                            ("admin", "Administrateur"),
                        ],
                        help_text="Rôle ciblé (optionnel, laisser vide pour tous)",
                        max_length=20,
                        null=True,
                        verbose_name="Public cible",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date après laquelle l'annonce ne sera plus visible",
                        null=True,
                        verbose_name="Date d'expiration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["teacher", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Module ciblé (optionnel, laisser vide pour une annonce générale)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="api.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-is_pinned", "-published_date"],
                "indexes": [
                    models.Index(
                        fields=["author", "published_date"],
                        name="api_announc_author__ff81ed_idx",
                    ),
                    models.Index(
                        fields=["module", "is_active"],
                        name="api_announc_module__49d189_idx",
                    ),
                    models.Index(
                        fields=["is_pinned", "published_date"],
                        name="api_announc_is_pinn_7aa5e6_idx",
                    ),
                    models.Index(
                        fields=["is_active", "published_date"],
                        name="api_announc_is_acti_4864a4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("exam", "Examen"),
                            ("assignment", "Devoir"),
                            ("project", "Projet"),
                            ("quiz", "Quiz"),
                            ("participation", "Participation"),
                            ("midterm", "Contrôle continu"),
                            ("final", "Examen final"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de note",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Note sur 20",
                        max_digits=5,
                        verbose_name="Note",
                    ),
                ),
                (
                    "max_grade",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Note maximale possible (par défaut 20)",
                        max_digits=5,
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire ou remarque sur la note",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "graded_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de notation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["teacher", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Noté par",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="api.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-graded_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "module"],
                        name="api_grade_student_23a2ea_idx",
                    ),
                    models.Index(
                        fields=["module", "grade_type"],
                        name="api_grade_module__3bf879_idx",
                    ),
                    models.Index(
                        fields=["graded_date"], name="api_grade_graded__08168b_idx"
                    ),
                ],
            },
        ),
    ]
