# Generated by Django 5.2.8 on 2025-11-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_announcement_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le message a été lu par le destinataire",
                        verbose_name="Lu",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure à laquelle le message a été lu",
                        null=True,
                        verbose_name="Date de lecture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient"],
                        name="api_chatmes_sender__c29444_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="api_chatmes_recipie_110a88_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="api_chatmes_created_ede6cd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Annonce"),
                            ("grade", "Note"),
                            ("message", "Message"),
                            ("enrollment", "Inscription"),
                            ("module", "Module"),
                            ("session", "Session de cours"),
                            ("resource", "Ressource"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de notification",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers la ressource concernée",
                        null=True,
                        verbose_name="Lien",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si la notification a été lue",
                        verbose_name="Lu",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure à laquelle la notification a été lue",
                        null=True,
                        verbose_name="Date de lecture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "related_announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.announcement",
                        verbose_name="Annonce concernée",
                    ),
                ),
                (
                    "related_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.grade",
                        verbose_name="Note concernée",
                    ),
                ),
                (
                    "related_module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.module",
                        verbose_name="Module concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="api_notific_recipie_28b188_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="api_notific_notific_574e18_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="api_notific_created_238c70_idx"
                    ),
                ],
            },
        ),
    ]
